import { 
  Home, 
  ClipboardList, 
  ShieldCheck, 
  Users, 
  User,
  ArrowUpFromLine,
  Wallet,
  Trophy,
  Gift,
  Users2,
  LineChart,
  FileText,
  Building2,
  Headphones,
  Award,
  CheckCircle2,
  TrendingUp,
  Star,
  Gamepad2,
  Diamond,
  Gem,
  Crown,
  Sparkles,
  Zap,
  Flame,
  Orbit
} from "lucide-react";

export const QUICK_ACTIONS = [
  { id: 'recharge', label: 'RECARGA', icon: Wallet },
  { id: 'withdraw', label: 'SAQUE', icon: ArrowUpFromLine },
  { id: 'box', label: 'CAIXA SORTE', icon: Gift },
  { id: 'team', label: 'EQUIPE', icon: Users2 },
  { id: 'company', label: 'EMPRESA', icon: Building2 },
  { id: 'tasks', label: 'TAREFA', icon: FileText },
  { id: 'records', label: 'REGISTOS', icon: ClipboardList },
  { id: 'support', label: 'SUPORTE', icon: Headphones },
];

export const COMPANY_INFO = {
  name: 'MOZA Investimentos S.A.',
  since: '2019',
  headquarters: 'Avenida 25 de Setembro, Prédio Moza, 4º Andar, Maputo, Moçambique',
  email: 'contacto@mozainvest.co.mz',
  phone: '+258 84 877 8905',
  license: 'MOZ-INV-2024-08X (Autorizada pelo Banco de Moçambique)',
  history: 'A Moza Investimentos S.A. surgiu em 2019 como a primeira plataforma moçambicana 100% dedicada à democratização do acesso aos mercados de capitais digitais. Através de uma tecnologia proprietária de arbitragem e micro-investimento, permitimos que milhares de moçambicanos participem no crescimento da economia digital global a partir de apenas 500 MZN.',
  mission: 'Empoderar cidadãos moçambicanos através de investimentos acessíveis e rentáveis no mercado digital, promovendo a inclusão financeira e a literacia económica em todo o país.',
  values: [
    { title: 'Inovação', description: 'Utilizamos tecnologia de ponta para simplificar o complexo mundo das finanças.' },
    { title: 'Transparência', description: 'Todos os ganhos e operações são auditáveis em tempo real pelos nossos investidores.' },
    { title: 'Integridade', description: 'Operamos sob os mais rigorosos padrões éticos e regulatórios de Moçambique.' },
    { title: 'Responsabilidade', description: 'Comprometemo-nos com o crescimento sustentável do capital dos nossos membros.' }
  ],
  certificates: [
    { id: 1, title: 'Certificado de Operação Digital', issuer: 'Autoridade Financeira de Maputo' },
    { id: 2, title: 'Selo de Segurança SSL 256-bit', issuer: 'GlobalSign Cloud' },
    { id: 3, title: 'Parceria Platina de Pagamentos', issuer: 'M-Pesa/e-Mola' }
  ]
};

export const NAV_ITEMS = [
  { id: 'home', label: 'INÍCIO', icon: Home },
  { id: 'tasks', label: 'TAREFA', icon: ClipboardList },
  { id: 'mines', label: 'MINAS', icon: Gamepad2 },
  { id: 'vip', label: 'VIP', icon: ShieldCheck },
  { id: 'team', label: 'EQUIPA', icon: Users },
  { id: 'profile', label: 'PERFIL', icon: User },
];

export const FINANCIAL_METHODS = [
  { 
    id: 'mpesa', 
    name: 'M-Pesa', 
    color: 'bg-[#e61c2b]', 
    delay: 'Instantâneo', 
    number: '848778905', 
    holder: 'PAULO JOAQUIM COMODALI',
  },
  { 
    id: 'emola', 
    name: 'e-Mola', 
    color: 'bg-[#ff6600]', 
    delay: 'Instantâneo', 
    number: '875376446', 
    holder: 'LUISA ZULANE MALUMBE',
  },
  { 
    id: 'bank', 
    name: 'Transferência Bancária', 
    color: 'bg-gold', 
    delay: '24-48h', 
    number: '0001 2233 4455', 
    holder: 'MOZA INVEST',
  },
  { 
    id: 'paypal', 
    name: 'PayPal', 
    color: 'bg-[#003087]', 
    delay: '1h-24h', 
    number: 'paulichocomedy@gmail.com', 
    holder: 'MOZA INVEST',
  },
];

export const DAILY_TASKS = [
  // VIP 1 - Total 36 MZN (2 tarefas de 18)
  { id: 21, title: 'Inscrever no Canal YouTube', reward: 50, category: 'ESPECIAL', time: '1min', vipLevel: 0, link: 'https://youtube.com/@mozainvest?si=XeLT5nrj9TbxnvIW', description: 'Ganhe 50 MZN e +15% de bónus no próximo depósito!' },
  { id: 1, title: 'Visualizar Publicidade Moza', reward: 18, category: 'MARKETING', time: '15s', vipLevel: 1 },
  { id: 2, title: 'Avaliar App na Play Store', reward: 18, category: 'FEEDBACK', time: '30s', vipLevel: 1 },
  
  // VIP 2 - Total 145 MZN (2 tarefas de 72.5)
  { id: 3, title: 'Análise de Gráfico Diário', reward: 72.5, category: 'ANÁLISE', time: '1min', vipLevel: 2 },
  { id: 4, title: 'Partilhar no WhatsApp Business', reward: 72.5, category: 'SOCIAL', time: '45s', vipLevel: 2 },
  
  // VIP 3 - Total 520 MZN (2 tarefas de 260)
  { id: 5, title: 'Auditoria de Transações Elites', reward: 260, category: 'FINANÇAS', time: '2min', vipLevel: 3 },
  { id: 6, title: 'Relatório de Mercado Semanal', reward: 260, category: 'PESQUISA', time: '3min', vipLevel: 3 },
  
  // VIP 4 - Total 2800 MZN (2 tarefas de 1400)
  { id: 7, title: 'Validar Lotes de Investimento', reward: 1400, category: 'OPERACIONAL', time: '5min', vipLevel: 4 },
  { id: 8, title: 'Consultoria de Ativos Digitais', reward: 1400, category: 'ESTRATÉGIA', time: '10min', vipLevel: 4 },
  
  // VIP 5 - Total 12500 MZN (2 tarefas de 6250)
  { id: 9, title: 'Aprovação de Crédito Institucional', reward: 6250, category: 'GESTÃO', time: '15min', vipLevel: 5 },
  { id: 10, title: 'Gestão de Fundo de Reserva', reward: 6250, category: 'DIRETORIA', time: '20min', vipLevel: 5 },

  // VIP 6 - Total 45000 MZN
  { id: 11, title: 'Supervisão de Mercado Platinum', reward: 22500, category: 'MASTER', time: '30min', vipLevel: 6 },
  { id: 12, title: 'Aprovação de Ativos Estratégicos', reward: 22500, category: 'DIRETORIA', time: '40min', vipLevel: 6 },

  // VIP 7 - Total 150000 MZN
  { id: 13, title: 'Análise Diamond de Riscos', reward: 75000, category: 'RISCO', time: '1h', vipLevel: 7 },
  { id: 14, title: 'Consumo de Dados Institucionais', reward: 75000, category: 'DADOS', time: '1h', vipLevel: 7 },

  // VIP 8 - Total 550000 MZN
  { id: 15, title: 'Protocolo Crown de Segurança', reward: 275000, category: 'SECURITY', time: '2h', vipLevel: 8 },
  { id: 16, title: 'Validação Transacional Global', reward: 275000, category: 'SYSTEM', time: '2h', vipLevel: 8 },

  // VIP 9 - Total 1800000 MZN
  { id: 17, title: 'Oráculo de Projeção Econômica', reward: 900000, category: 'FUTURE', time: '3h', vipLevel: 9 },
  { id: 18, title: 'Gestão de Venture Capital', reward: 900000, category: 'INVEST', time: '4h', vipLevel: 9 },

  // VIP 10 - Total 7000000 MZN
  { id: 19, title: 'Protocolo Cosmic de Ativos', reward: 3500000, category: 'ORIGIN', time: '6h', vipLevel: 10 },
  { id: 20, title: 'Governança Total de Ecossistema', reward: 3500000, category: 'GOD_MODE', time: '8h', vipLevel: 10 },
];

export const TEAM_LEVELS = [
  { level: 'Nível 1', commission: '10%', count: 5, totalProfit: 1250 },
  { level: 'Nível 2', commission: '5%', count: 12, totalProfit: 840 },
  { level: 'Nível 3', commission: '2%', count: 3, totalProfit: 110 },
];

export const VIP_LEVELS = [
  { 
    id: 1, 
    name: 'VIP 1', 
    badge: 'PREMIUM',
    investment: 700, 
    dailyReturn: 36,
    isPremium: true,
    icon: Award,
    color: 'from-blue-400 to-blue-600',
    benefits: ['Acesso a tarefas básicas', 'Saque antecipado', 'Suporte prioritário']
  },
  { 
    id: 2, 
    name: 'VIP 2', 
    badge: 'LUXURY',
    investment: 2500, 
    dailyReturn: 145,
    isPremium: false,
    icon: ShieldCheck,
    color: 'from-purple-400 to-purple-600',
    benefits: ['Comissões de rede +5%', 'Tarefas exclusivas', 'Bónus de ativação']
  },
  { 
    id: 3, 
    name: 'VIP 3', 
    badge: 'ELITE',
    investment: 8000, 
    dailyReturn: 520,
    isPremium: false,
    icon: Trophy,
    color: 'from-emerald-400 to-emerald-600',
    benefits: ['Gerente de conta VIP', 'Retornos diários altos', 'Certificado de investidor']
  },
  { 
    id: 4, 
    name: 'VIP 4', 
    badge: 'ATIVO',
    investment: 35000, 
    dailyReturn: 2800,
    isPremium: false,
    icon: Diamond,
    color: 'from-cyan-400 to-cyan-600',
    benefits: ['Participação nos lucros', 'Acesso total a Caixa Sorte', 'Eventos exclusivos']
  },
  { 
    id: 5, 
    name: 'VIP 5', 
    badge: 'GOLDEN',
    investment: 150000, 
    dailyReturn: 12500,
    isPremium: false,
    icon: Gem,
    color: 'from-gold via-yellow-500 to-gold',
    benefits: ['Retorno Máximo', 'Saques Ilimitados', 'Acesso Prioritário Global', 'Bónus de Rede 15%']
  },
  { 
    id: 6, 
    name: 'VIP 6', 
    badge: 'PLATINUM',
    investment: 500000, 
    dailyReturn: 45000,
    isPremium: false,
    icon: Crown,
    color: 'from-gray-300 via-white to-gray-400',
    benefits: ['Gestor VIP 24/7', 'Eventos Internacionais', 'Cartão Metal Exclusivo']
  },
  { 
    id: 7, 
    name: 'VIP 7', 
    badge: 'DIAMOND',
    investment: 1500000, 
    dailyReturn: 150000,
    isPremium: false,
    icon: Sparkles,
    color: 'from-blue-200 via-blue-400 to-blue-200',
    benefits: ['Participação em Dividendos', 'Viagem Anual All-Inclusive', 'Seguro de Ativos']
  },
  { 
    id: 8, 
    name: 'VIP 8', 
    badge: 'CROWN',
    investment: 5000000, 
    dailyReturn: 550000,
    isPremium: false,
    icon: Zap,
    color: 'from-yellow-300 via-orange-400 to-yellow-300',
    benefits: ['Conselho Consultivo', 'Jato Privado (1x/ano)', 'Residência Digital']
  },
  { 
    id: 9, 
    name: 'VIP 9', 
    badge: 'ORACLE',
    investment: 15000000, 
    dailyReturn: 1800000,
    isPremium: false,
    icon: Flame,
    color: 'from-red-400 via-orange-500 to-red-600',
    benefits: ['Governança Institucional', 'Fundo de Venture Moza', 'Imortalidade Financeira']
  },
  { 
    id: 10, 
    name: 'VIP 10', 
    badge: 'COSMIC',
    investment: 50000000, 
    dailyReturn: 7000000,
    isPremium: false,
    icon: Orbit,
    color: 'from-indigo-400 via-purple-500 to-pink-500',
    benefits: ['Controle de Ecossistema', 'Herança Transgeracional', 'Status Lendário']
  },
];

export const LANGUAGES = [
  { id: 'pt', name: 'Português', flag: '🇲🇿' },
  { id: 'en', name: 'English', flag: '🇺🇸' },
  { id: 'ny', name: 'Chichewa', flag: '🇲🇼' },
  { id: 'nh', name: 'Nhungué', flag: '🇲🇿' },
  { id: 'sen', name: 'Masena', flag: '🇲🇿' },
  { id: 'tsg', name: 'Changana', flag: '🇲🇿' },
  { id: 'vmw', name: 'Macua', flag: '🇲🇿' },
  { id: 'mde', name: 'Makonde', flag: '🇲🇿' },
  { id: 'zu', name: 'Zulu', flag: '🇿🇦' },
];

export const TRANSLATIONS: Record<string, any> = {
  pt: {
    home: 'INÍCIO',
    balance: 'SALDO TOTAL',
    withdraw: 'LEVANTAR',
    deposit: 'DEPÓSITO',
    tasks: 'TAREFAS',
    vip: 'VIP',
    profile: 'PERFIL',
    invite: 'CONVIDAR',
    records: 'REGISTOS',
    daily_earnings: 'GANHOS DIÁRIOS',
    active_now: 'ATIVO AGORA',
    start_earning: 'COMEÇAR A GANHAR',
    my_team: 'MINHA EQUIPA',
    team: 'EQUIPA',
    settings: 'DEFINIÇÕES',
    logout: 'SAIR',
    edit_profile: 'EDITAR PERFIL',
    save: 'GUARDAR',
    limit_reached: 'Limite atingido!',
    mines: 'MINAS',
  },
  en: {
    home: 'HOME',
    balance: 'TOTAL BALANCE',
    withdraw: 'WITHDRAW',
    deposit: 'DEPOSIT',
    tasks: 'TASKS',
    vip: 'VIP',
    profile: 'PROFILE',
    invite: 'INVITE',
    records: 'RECORDS',
    daily_earnings: 'DAILY EARNINGS',
    active_now: 'ACTIVE NOW',
    start_earning: 'START EARNING',
    my_team: 'MY TEAM',
    team: 'TEAM',
    settings: 'SETTINGS',
    logout: 'LOGOUT',
    edit_profile: 'EDIT PROFILE',
    save: 'SAVE',
    limit_reached: 'Limit reached!',
    mines: 'MINES',
  },
  ny: {
    home: 'PANYUMBA',
    balance: 'NDALAMA ZONSE',
    withdraw: 'TULUTSA',
    deposit: 'IKA',
    tasks: 'NTCHITO',
    vip: 'VIP',
    profile: 'MBIRI',
    invite: 'ITANANI',
    records: 'ZOFALITSIDWA',
    daily_earnings: 'ZAPEZEDWA LERO',
    active_now: 'ULIPO PANO',
    start_earning: 'YAMBANI KUPEZA',
    my_team: 'TIMU YANGA',
    team: 'TIMU',
    settings: 'ZOKONZERA',
    logout: 'TULUKANI',
    edit_profile: 'KONZANI MBIRI',
    save: 'SUNGANI',
    limit_reached: 'Mwafika malire!',
  },
  nh: {
    home: 'PAMUI',
    balance: 'KOBIDI YENSE',
    withdraw: 'KUBULUSA',
    deposit: 'KUICHA',
    tasks: 'BASA',
    vip: 'VIP',
    profile: 'PERFIL',
    invite: 'KUCHEMERA',
    records: 'REJISTO',
    daily_earnings: 'GANYU YA LERO',
    active_now: 'ULI PANO',
    start_earning: 'YAMBA KUGANYA',
    my_team: 'EKIPA YANGU',
    team: 'EKIPA',
    settings: 'DEFINISOES',
    logout: 'KUBULUKA',
    edit_profile: 'CHinja PERFIL',
    save: 'KUKOYA',
    limit_reached: 'Limit wafika!',
  },
  sen: {
    home: 'PAMUI',
    balance: 'KOBIDI YENSENE',
    withdraw: 'KUBULUSA',
    deposit: 'KUIKA',
    tasks: 'BASA',
    vip: 'VIP',
    profile: 'MBIRI',
    invite: 'KUCEMERA',
    records: 'REJISTO',
    daily_earnings: 'GANYU YA LEROU',
    active_now: 'ULIPANO',
    start_earning: 'YAMBA KUGANYA',
    my_team: 'EKIPA YANGU',
    team: 'EKIPA',
    settings: 'DEFINISOES',
    logout: 'KUBULUWA',
    edit_profile: 'CHINJA PERFIL',
    save: 'KUKOYA',
    limit_reached: 'Limit wafika!',
  },
  tsg: {
    home: 'KAYA',
    balance: 'MALI HINKWAYO',
    withdraw: 'KUKONTSA',
    deposit: 'KUPAKATA',
    tasks: 'MINTIRO',
    vip: 'VIP',
    profile: 'TIKO',
    invite: 'RHAMBA',
    records: 'TSALWA',
    daily_earnings: 'MABANZA YA SIKU',
    active_now: 'U KONA',
    start_earning: 'SUNGA KUHOLA',
    my_team: 'NDZAVU YANGA',
    team: 'NDZAVU',
    settings: 'SWIKONTZELO',
    logout: 'HUMA',
    edit_profile: 'LULAMISA TIKO',
    save: 'HETISA',
    limit_reached: 'Mpfuka wu herile!',
  },
  vmw: {
    home: 'OWANI',
    balance: 'MUSURUKHU WOTHENE',
    withdraw: 'OKUMIHA',
    deposit: 'OHELA',
    tasks: 'MITEKO',
    vip: 'VIP',
    profile: 'MBIRI',
    invite: 'WITCHANA',
    records: 'MASIPO',
    daily_earnings: 'SOPHYA NA LELO',
    active_now: 'OLI VA',
    start_earning: 'OPHAZA OPHWANYA',
    my_team: 'EQUIPA AKA',
    team: 'EQUIPA',
    settings: 'MIRUTHO',
    logout: 'OKHuma',
    edit_profile: 'OREHERYA MBIRI',
    save: 'OSUNGA',
    limit_reached: 'Ophiya omakuchulo!',
  },
  mde: {
    home: 'KAYA',
    balance: 'NDIYELE YOSHE',
    withdraw: 'KUTULUSHA',
    deposit: 'KUWIKA',
    tasks: 'MADENGO',
    vip: 'VIP',
    profile: 'MBIRI',
    invite: 'KULALIKA',
    records: 'REJISTO',
    daily_earnings: 'GANHO YA LELU',
    active_now: 'ULI PANO',
    start_earning: 'TANDA KUGANYA',
    my_team: 'EKIPA YANGU',
    team: 'EKIPA',
    settings: 'DEFINISOES',
    logout: 'KULAUA',
    edit_profile: 'BADILI MBIRI',
    save: 'KULINDA',
    limit_reached: 'Mupaka umewika!',
  },
  zu: {
    home: 'EKHAYA',
    balance: 'IMALI YONKE',
    withdraw: 'Khipha',
    deposit: 'Faka',
    tasks: 'Imisebenzi',
    vip: 'VIP',
    profile: 'Iphrofayela',
    invite: 'Mema',
    records: 'Amarekhodi',
    daily_earnings: 'Imali yanamuhla',
    active_now: 'Ukhona manje',
    start_earning: 'Qala ukuhola',
    my_team: 'Ithimba lami',
    team: 'Ithimba',
    settings: 'Izilungiselelo',
    logout: 'Phuma',
    edit_profile: 'Hlela iphrofayela',
    save: 'Gcina',
    limit_reached: 'Umkhawulo ufinyelele!',
  }
};
