import { 
  Home, 
  ClipboardList, 
  ShieldCheck, 
  Users, 
  User,
  ArrowUpFromLine,
  Wallet,
  Trophy,
  Gift,
  Users2,
  LineChart,
  FileText,
  Building2,
  Headphones,
  Award,
  CheckCircle2,
  TrendingUp,
  Star
} from "lucide-react";

export const QUICK_ACTIONS = [
  { id: 'recharge', label: 'RECARGA', icon: Wallet },
  { id: 'withdraw', label: 'SAQUE', icon: ArrowUpFromLine },
  { id: 'box', label: 'CAIXA SORTE', icon: Gift },
  { id: 'team', label: 'EQUIPE', icon: Users2 },
  { id: 'company', label: 'EMPRESA', icon: Building2 },
  { id: 'tasks', label: 'TAREFA', icon: FileText },
  { id: 'records', label: 'REGISTOS', icon: ClipboardList },
  { id: 'support', label: 'SUPORTE', icon: Headphones },
];

export const COMPANY_INFO = {
  name: 'MOZA Investimentos S.A.',
  since: '2019',
  headquarters: 'Maputo, Moçambique',
  license: 'MOZ-INV-2024-08X',
  mission: 'Empoderar cidadãos moçambicanos através de investimentos acessíveis e rentáveis no mercado digital.',
  certificates: [
    { id: 1, title: 'Certificado de Operação Digital', issuer: 'Autoridade Financeira de Maputo' },
    { id: 2, title: 'Selo de Segurança SSL 256-bit', issuer: 'GlobalSign Cloud' },
    { id: 3, title: 'Parceria Platina de Pagamentos', issuer: 'M-Pesa/e-Mola' }
  ]
};

export const NAV_ITEMS = [
  { id: 'home', label: 'INÍCIO', icon: Home },
  { id: 'tasks', label: 'TAREFA', icon: ClipboardList },
  { id: 'vip', label: 'VIP', icon: ShieldCheck },
  { id: 'team', label: 'EQUIPA', icon: Users },
  { id: 'profile', label: 'PERFIL', icon: User },
];

export const FINANCIAL_METHODS = [
  { id: 'mpesa', name: 'M-Pesa', color: 'bg-[#e61c2b]', delay: 'Instantâneo', number: '848778905', holder: 'PAULO JOAQUIM COMODALI' },
  { id: 'emola', name: 'e-Mola', color: 'bg-[#ff6600]', delay: 'Instantâneo', number: '875376446', holder: 'LUISA ZULANE MALUMBE' },
  { id: 'bank', name: 'Transferência Bancária', color: 'bg-gold', delay: '24-48h', number: '0001 2233 4455', holder: 'MOZA INVEST' },
];

export const DAILY_TASKS = [
  { id: 1, title: 'Assistir Anúncio Premium', reward: 50, category: 'PUBLICIDADE', time: '30s' },
  { id: 2, title: 'Validar Transação VIP 4', reward: 120, category: 'VALIDAÇÃO', time: '1min' },
  { id: 3, title: 'Compartilhar Link Diário', reward: 30, category: 'SOCIAL', time: '2min' },
  { id: 4, title: 'Reclame Recompensa Log-in', reward: 10, category: 'DIÁRIO', time: 'Agora' },
  { id: 5, title: 'Feedback de Mercado', reward: 80, category: 'PESQUISA', time: '5min' },
];

export const TEAM_LEVELS = [
  { level: 'Nível 1', commission: '10%', count: 5, totalProfit: 1250 },
  { level: 'Nível 2', commission: '5%', count: 12, totalProfit: 840 },
  { level: 'Nível 3', commission: '2%', count: 3, totalProfit: 110 },
];

export const VIP_LEVELS = [
  { 
    id: 1, 
    name: 'VIP 1', 
    badge: 'PREMIUM',
    investment: 700, 
    dailyReturn: 36,
    isPremium: true,
    benefits: ['Acesso a tarefas básicas', 'Saque antecipado', 'Suporte prioritário']
  },
  { 
    id: 2, 
    name: 'VIP 2', 
    badge: 'LUXURY',
    investment: 2500, 
    dailyReturn: 145,
    isPremium: false,
    benefits: ['Comissões de rede +5%', 'Tarefas exclusivas', 'Bónus de ativação']
  },
  { 
    id: 3, 
    name: 'VIP 3', 
    badge: 'ELITE',
    investment: 8000, 
    dailyReturn: 520,
    isPremium: false,
    benefits: ['Gerente de conta VIP', 'Retornos diários altos', 'Certificado de investidor']
  },
  { 
    id: 4, 
    name: 'VIP 4', 
    badge: 'ATIVO',
    investment: 35000, 
    dailyReturn: 2800,
    isPremium: false,
    benefits: ['Participação nos lucros', 'Acesso total a Caixa Sorte', 'Eventos exclusivos']
  },
  { 
    id: 5, 
    name: 'VIP 5', 
    badge: 'GOLDEN',
    investment: 150000, 
    dailyReturn: 12500,
    isPremium: false,
    benefits: ['Retorno Máximo', 'Saques Ilimitados', 'Acesso Prioritário Global', 'Bónus de Rede 15%']
  },
];

export const LANGUAGES = [
  { id: 'pt', name: 'Português', flag: '🇲🇿' },
  { id: 'en', name: 'English', flag: '🇺🇸' },
  { id: 'ny', name: 'Chichewa', flag: '🇲🇼' },
  { id: 'nh', name: 'Nhungué', flag: '🇲🇿' },
  { id: 'sen', name: 'Masena', flag: '🇲🇿' },
  { id: 'tsg', name: 'Changana', flag: '🇲🇿' },
  { id: 'vmw', name: 'Macua', flag: '🇲🇿' },
  { id: 'mde', name: 'Makonde', flag: '🇲🇿' },
  { id: 'zu', name: 'Zulu', flag: '🇿🇦' },
];

export const TRANSLATIONS: Record<string, any> = {
  pt: {
    home: 'INÍCIO',
    balance: 'SALDO TOTAL',
    withdraw: 'LEVANTAR',
    deposit: 'DEPÓSITO',
    tasks: 'TAREFAS',
    vip: 'VIP',
    profile: 'PERFIL',
    invite: 'CONVIDAR',
    records: 'REGISTOS',
    daily_earnings: 'GANHOS DIÁRIOS',
    active_now: 'ATIVO AGORA',
    start_earning: 'COMEÇAR A GANHAR',
    my_team: 'MINHA EQUIPA',
    team: 'EQUIPA',
    settings: 'DEFINIÇÕES',
    logout: 'SAIR',
    edit_profile: 'EDITAR PERFIL',
    save: 'GUARDAR',
    limit_reached: 'Limite atingido!',
  },
  en: {
    home: 'HOME',
    balance: 'TOTAL BALANCE',
    withdraw: 'WITHDRAW',
    deposit: 'DEPOSIT',
    tasks: 'TASKS',
    vip: 'VIP',
    profile: 'PROFILE',
    invite: 'INVITE',
    records: 'RECORDS',
    daily_earnings: 'DAILY EARNINGS',
    active_now: 'ACTIVE NOW',
    start_earning: 'START EARNING',
    my_team: 'MY TEAM',
    team: 'TEAM',
    settings: 'SETTINGS',
    logout: 'LOGOUT',
    edit_profile: 'EDIT PROFILE',
    save: 'SAVE',
    limit_reached: 'Limit reached!',
  },
  ny: {
    home: 'PANYUMBA',
    balance: 'NDALAMA ZONSE',
    withdraw: 'TULUTSA',
    deposit: 'IKA',
    tasks: 'NTCHITO',
    vip: 'VIP',
    profile: 'MBIRI',
    invite: 'ITANANI',
    records: 'ZOFALITSIDWA',
    daily_earnings: 'ZAPEZEDWA LERO',
    active_now: 'ULIPO PANO',
    start_earning: 'YAMBANI KUPEZA',
    my_team: 'TIMU YANGA',
    team: 'TIMU',
    settings: 'ZOKONZERA',
    logout: 'TULUKANI',
    edit_profile: 'KONZANI MBIRI',
    save: 'SUNGANI',
    limit_reached: 'Mwafika malire!',
  },
  nh: {
    home: 'PAMUI',
    balance: 'KOBIDI YENSE',
    withdraw: 'KUBULUSA',
    deposit: 'KUICHA',
    tasks: 'BASA',
    vip: 'VIP',
    profile: 'PERFIL',
    invite: 'KUCHEMERA',
    records: 'REJISTO',
    daily_earnings: 'GANYU YA LERO',
    active_now: 'ULI PANO',
    start_earning: 'YAMBA KUGANYA',
    my_team: 'EKIPA YANGU',
    team: 'EKIPA',
    settings: 'DEFINISOES',
    logout: 'KUBULUKA',
    edit_profile: 'CHinja PERFIL',
    save: 'KUKOYA',
    limit_reached: 'Limit wafika!',
  },
  sen: {
    home: 'PAMUI',
    balance: 'KOBIDI YENSENE',
    withdraw: 'KUBULUSA',
    deposit: 'KUIKA',
    tasks: 'BASA',
    vip: 'VIP',
    profile: 'MBIRI',
    invite: 'KUCEMERA',
    records: 'REJISTO',
    daily_earnings: 'GANYU YA LEROU',
    active_now: 'ULIPANO',
    start_earning: 'YAMBA KUGANYA',
    my_team: 'EKIPA YANGU',
    team: 'EKIPA',
    settings: 'DEFINISOES',
    logout: 'KUBULUWA',
    edit_profile: 'CHINJA PERFIL',
    save: 'KUKOYA',
    limit_reached: 'Limit wafika!',
  },
  tsg: {
    home: 'KAYA',
    balance: 'MALI HINKWAYO',
    withdraw: 'KUKONTSA',
    deposit: 'KUPAKATA',
    tasks: 'MINTIRO',
    vip: 'VIP',
    profile: 'TIKO',
    invite: 'RHAMBA',
    records: 'TSALWA',
    daily_earnings: 'MABANZA YA SIKU',
    active_now: 'U KONA',
    start_earning: 'SUNGA KUHOLA',
    my_team: 'NDZAVU YANGA',
    team: 'NDZAVU',
    settings: 'SWIKONTZELO',
    logout: 'HUMA',
    edit_profile: 'LULAMISA TIKO',
    save: 'HETISA',
    limit_reached: 'Mpfuka wu herile!',
  },
  vmw: {
    home: 'OWANI',
    balance: 'MUSURUKHU WOTHENE',
    withdraw: 'OKUMIHA',
    deposit: 'OHELA',
    tasks: 'MITEKO',
    vip: 'VIP',
    profile: 'MBIRI',
    invite: 'WITCHANA',
    records: 'MASIPO',
    daily_earnings: 'SOPHYA NA LELO',
    active_now: 'OLI VA',
    start_earning: 'OPHAZA OPHWANYA',
    my_team: 'EQUIPA AKA',
    team: 'EQUIPA',
    settings: 'MIRUTHO',
    logout: 'OKHuma',
    edit_profile: 'OREHERYA MBIRI',
    save: 'OSUNGA',
    limit_reached: 'Ophiya omakuchulo!',
  },
  mde: {
    home: 'KAYA',
    balance: 'NDIYELE YOSHE',
    withdraw: 'KUTULUSHA',
    deposit: 'KUWIKA',
    tasks: 'MADENGO',
    vip: 'VIP',
    profile: 'MBIRI',
    invite: 'KULALIKA',
    records: 'REJISTO',
    daily_earnings: 'GANHO YA LELU',
    active_now: 'ULI PANO',
    start_earning: 'TANDA KUGANYA',
    my_team: 'EKIPA YANGU',
    team: 'EKIPA',
    settings: 'DEFINISOES',
    logout: 'KULAUA',
    edit_profile: 'BADILI MBIRI',
    save: 'KULINDA',
    limit_reached: 'Mupaka umewika!',
  },
  zu: {
    home: 'EKHAYA',
    balance: 'IMALI YONKE',
    withdraw: 'Khipha',
    deposit: 'Faka',
    tasks: 'Imisebenzi',
    vip: 'VIP',
    profile: 'Iphrofayela',
    invite: 'Mema',
    records: 'Amarekhodi',
    daily_earnings: 'Imali yanamuhla',
    active_now: 'Ukhona manje',
    start_earning: 'Qala ukuhola',
    my_team: 'Ithimba lami',
    team: 'Ithimba',
    settings: 'Izilungiselelo',
    logout: 'Phuma',
    edit_profile: 'Hlela iphrofayela',
    save: 'Gcina',
    limit_reached: 'Umkhawulo ufinyelele!',
  }
};
